using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace YuanSheng;

public static class MainClass
{
    public static void Main(string[] args){}
}

[Generator]
public class EvtChangedGenerator : IIncrementalGenerator
{
    // 定义报错规则
    static readonly DiagnosticDescriptor nonPartialPropertyRule = new(
        id: "NM000",
        title: "属性应为partial",
        messageFormat: "属性 {0} 有[EvtChanged]后, 必须为partial",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 创建语法提供者
        var properties = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m.HasValue) // 过滤掉无效项
            .Select(static (m, _) => m!.Value); // 解包 Nullable

        // 注册输出
        context.RegisterSourceOutput(properties, static (spc, source) => Execute(spc, source));
    }

    // 步骤1的快速筛选：只要有 Attribute 的属性都放行（不再强制必须 partial，以便后续报错）
    static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is PropertyDeclarationSyntax { AttributeLists.Count: > 0 };
    }

    // 步骤2的语义筛选：提取符号、位置信息以及是否为 partial
    static (IPropertySymbol Symbol, Location Location, bool IsPartial)? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var propertyDeclaration = (PropertyDeclarationSyntax)context.Node;

        var model = context.SemanticModel;
        if (model.GetDeclaredSymbol(propertyDeclaration) is not IPropertySymbol propertySymbol)
            return null;

        // 检查特性名称
        if (!propertySymbol.GetAttributes().Any(ad => ad.AttributeClass?.Name == "EvtChangedAttribute"))
            return null;

        // 检查是否有 partial 修饰符
        bool isPartial = propertyDeclaration.Modifiers.Any(m => m.Text == "partial");

        return (propertySymbol, propertyDeclaration.GetLocation(), isPartial);
    }

    // 步骤3：生成代码或报错
    static void Execute(SourceProductionContext context, (IPropertySymbol Symbol, Location Location, bool IsPartial) source)
    {
        var (propertySymbol, location, isPartial) = source;

        // 如果不是 partial，则报错并停止生成
        if (!isPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(nonPartialPropertyRule, location, propertySymbol.Name));
            return;
        }

        string classSource = ProcessClass(propertySymbol);
        
        string safeTypeName = propertySymbol.ContainingType.ToDisplayString().Replace('.', '_').Replace('+', '_');
        context.AddSource($"{safeTypeName}_{propertySymbol.Name}_Notify.g.cs", SourceText.From(classSource, Encoding.UTF8));
    }

    static string ProcessClass(IPropertySymbol propertySymbol)
    {
        var containingClass = propertySymbol.ContainingType;
        var namespaceName = containingClass.ContainingNamespace.ToDisplayString();
        var className = containingClass.Name;
        var propertyName = propertySymbol.Name;
        var propertyType = propertySymbol.Type.ToDisplayString();

        string propertyAccess = GetAccessModifier(propertySymbol.DeclaredAccessibility);
        var setMethod = propertySymbol.SetMethod;
        string setModifier = (setMethod != null && setMethod.DeclaredAccessibility != propertySymbol.DeclaredAccessibility)
            ? GetAccessModifier(setMethod.DeclaredAccessibility) + " "
            : "";

        // 1. 将所有嵌套类由外到内收集起来 (父类 -> 内部类)
        var classHierarchy = new System.Collections.Generic.List<INamedTypeSymbol>();
        var currentClass = containingClass;
        while (currentClass != null)
        {
            classHierarchy.Insert(0, currentClass);
            currentClass = currentClass.ContainingType;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        string indent = "    "; // 基础缩进（4个空格）

        // 2. 依次生成外部类的开头
        foreach (var cls in classHierarchy)
        {
            string typeKeyword = cls.IsRecord 
                ? (cls.IsValueType ? "record struct" : "record") 
                : (cls.IsValueType ? "struct" : "class");
            
            string classAccess = GetAccessModifier(cls.DeclaredAccessibility);

            sb.AppendLine($"{indent}{classAccess} partial {typeKeyword} {cls.Name}");
            sb.AppendLine($"{indent}{{");
            indent += "    "; // 每次更深一层，增加缩进
        }

        // 3. 生成属性主体和事件记录结构（使用当前的 indent）
        sb.AppendLine($"{indent}{propertyAccess} partial {propertyType} {propertyName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    get => field;");
        sb.AppendLine($"{indent}    {setModifier}set");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var oldValue = field; ");
        sb.AppendLine($"{indent}        field = value;");
        sb.AppendLine($"{indent}        new Evt{propertyName}Changed(this, oldValue, value).Forget();");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}{propertyAccess} record Evt{propertyName}Changed(");
        sb.AppendLine($"{indent}    {className} {className},");
        sb.AppendLine($"{indent}    {propertyType} OldValue,");
        sb.AppendLine($"{indent}    {propertyType} NewValue) : GeneralPreview.EvtForgetBase;");

        // 4. 依次关闭大括号
        for (int i = 0; i < classHierarchy.Count; i++)
        {
            indent = indent.Substring(0, indent.Length - 4); // 退回缩进
            sb.AppendLine($"{indent}}}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    static string GetAccessModifier(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.Public => "public",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "public"
        };
    }
}
